apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: academic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: academic-platform-authservice:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://authdb:5432/authdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: academic
spec:
  selector:
    app: authservice
  ports:
    - port: 8081
      targetPort: 8081