apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  namespace: academic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: academic-platform-notificationservice:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://notificationdb:5432/notificationdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  namespace: academic
spec:
  selector:
    app: notificationservice
  ports:
    - port: 8085
      targetPort: 8085